dist: xenial
sudo: required
language: python
python:
- '3.6'
stages:
- test
- name: deploy
  if: tag =~ cache OR tag =~ compare_versions OR tag =~ overlap
before_install:
- pip install -r requirements.txt
script:
- python3 -m pytest cache/lru_cache compare_versions/compare_versions overlap/overlap
- codecov
before_deploy:
- cd $(bash before_deploy.sh)
- cp ../README.md ./
- cp ../LICENSE.txt ./
- cp ../setup.cfg ./
deploy:
  provider: pypi
  user: carlos-ferras
  password:
    secure: Mgx9NiYvAroYeFz9cTUU4kSJrs+IhpKFOKCqsNYW/3hhpY4pLhaY8urdX77moCY70AD+3vWGau7aBqHWW1gw9gWCjF5vx/XD2y4y7TMXfmehfFlOmeJF4Vh2T4BCAAGqG6Gj557LXX7e7Y08Zuoq4p5Xi0MSk+4G3/Z9AMY1KpV74xPneblaafn5rq0+0SWHg3FIAcspAMUmUjW5Cr3O6XFsduWBKQu35ezve/OxXOASFKXgOATgHDLVs7j3mvoeZ0lzc4E5Ze9stdy26BflxyvDH6/lKE7l5M+JTPdKAKdIDuVhpuJCrge23SFRP1VrWsIw+Su0FuoIYtyChDOjG/WvDrFVWd9NW23PW3dO/Rloc5VIq+RYXCklFfwY0+eO9oRYtySCJWBtnkPyBJ6nd/jmNJAmVvawZtGAOBwbsxSLTo6RUhMLwO+asFAEsiCN+LcNpjv5V2hIof9gXXsORaJEYuutqx7txJT/U7xBQpghxB22Q6Oct+P9Hwxw1CK45D0Jhq5H4zXjbYZGOCRycmEfFIN2fuX2de3hNaPTxRnn7SY81HHRZmQHAJf62a6qhcAfMfNdizfabbStKWPK74VWuv+Y5J+GK8QPppIxyhbi9I+OWecNZNkT4xZWqZdr9LWMNqiYKCGqgM44DM8zxV8nNCVzC9q8eML5rx5E7wY=
  on:
    tags: true
  skip_existing: true
